### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by RisingInIris2017**
Dear Impelon!
Your lovely Disenchanter mod is quite adorable and useful.
I would like to make it translated into Chinese Simplified, 
so that there will be more players loving your brilliant work.
Would you kind-hearted man have this small lang file merged?
Thanks a ton in advance! :)

### CODE REVIEW

**Comment by Impelon** [comment]
Hm, so the thing is, I already have a chinese translation waiting for release in the [update-branch](https://github.com/Impelon/Disenchanter/blob/1.12-update/src/main/resources/assets/disenchanter/lang/zh_cn.lang).
Did you use that as your template? They seem pretty similar. 

However, the main problem is, that I do not have the time to release a full update.

**Comment by Impelon** [comment]
I am however thankful, that you are contributing ^^

**Comment by RisingInIris2017** [comment]
> Hm, so the thing is, I already have a chinese translation waiting for release in the [https://github.com/Impelon/Disenchanter/blob/1.12-update/src/main/resources/assets/disenchanter/lang/zh_cn.lang](update-branch).

Ah, thanks for your reply. 👍 
But when I created my version of zh_CN.lang,  I hadn't found such an lang file existing, and when I click this link now, it is a 404 page.
I still have problem to find the lang file that you mentioned.
I will keep this lang file updating, so you can have it merged whenever you need some Chinese translations. 
It's nice of you to reply and tell me this, thanks again!

**Comment by Impelon** [comment]
Ah, yes, sorry I messed up the link. I've updated my comment.

**Comment by RisingInIris2017** [comment]
I've read that link, so there is an existing language file.
And that is almost the same as mine, so you could use that tho.
I will keep watching this project and make my lang file updated asap.
Thanks all the same! :)

**Pull request closed without merging**
