### PR TITLE
Add blacklists to config

### PR DESCRIPTION
**Pull request by democat3457**
Adds item and enchantment blacklists to config, such that items cannot be disenchanted or certain enchantments cannot be removed.

### CODE REVIEW

**Comment by Impelon** [comment]
Hey! 
First of all thanks for contributing to my project!

I like your idea and I think it would provide value to the mod, so overall I want to add your contribution to the mod.
But I'd like to change your implementation a bit before adding it to the main-branch, therefore I'd appreciate if you can change the target/base of the pull-request to the `1.12-update`-branch.
Also I should really sort out the legal part of this... either you get added as contributor in the license file, or we need to arrange something else.

**Comment by democat3457** [comment]
Gotcha! I don't really see a legal problem here since the license just requires it to be displayed on derivatives or redistributions, and I didn't change the license.

**Comment by Impelon** [comment]
Yes, the problem is not necessarily linked to the license, but instead to the fact that you technically own the code you contributed, thus you retain copyright of part of the project. This should be reflected in some way in the files of the project, or it needs to be clear that contributors give up copyright to their contributions in some way.
For example ThermalExpansion makes it clear, that you give up copyright to your contributions: https://github.com/CoFH/ThermalExpansion/blob/1.12/README.md

On another note, you technically can distribute your contribution under another license, since BSD does not enforce you to use BSD for derived works: https://softwareengineering.stackexchange.com/questions/185566/does-a-bsd-licensed-project-need-a-signed-statement-from-each-contributor

Here is another explanation: https://haacked.com/archive/2006/01/26/WhoOwnstheCopyrightforAnOpenSourceProject.aspx/

I think an easy and fair way to do this, would be for me to introduce an contributors.md-file where you explicitly agree that your contributions are licensed with BSD, etc. Of course you would need to agree with that; I'll sort something out in the comming week(s).

**Comment by democat3457** [comment]
Sure; I'd be fine with the contributors.md file.

**Comment by Impelon** [comment]
Hello again!

After a bit of thinking and tinkering I've arrived at a CONTRIBUTORS.md-file that should be acceptable.
You can find it in the root of the `1.12-update`-branch. 
If you agree to the terms of contributing laid out in that file, please add your name to the list in the format specified.
You will probably have to merge the updated branch into your feature-branch to do this.

**Comment by democat3457** [comment]
Added!

**Comment by Impelon** [comment]
Great!
Thanks again for your contribution, I am sorry I made it kind of complicated. This was the first "bigger" contribution I had on one of my projects, so I thought I'd better make it right.

**Comment by democat3457** [comment]
All good!

**Pull request merged**
