### PR TITLE
Create zh_cn.lang

### PR DESCRIPTION
**Pull request by suoyukii**

### CODE REVIEW

**Comment by Impelon** [comment]
Hey, so thanks for your interest in contributing to my mod!
Thing is as I've stated in #43 I already have a chinese translation for the mod ready, when I find the time to update it. You can view it [here](https://github.com/Impelon/Disenchanter/commit/05b8add1c95a7b798d5f0d8c344e1fa37313fa7a).

If you think your translation is more accurate I can add yours instead, but otherwise I apologize that I cannot honour your work another way.

**Comment by suoyukii** [comment]
Add a zh_cn.lang, multiple contrast confirmed translation file to the texture package.

**Comment by suoyukii** [comment]
.minecraft/resourcepacks/Chinese_translation_test/assets/disenchanter/lang/zh_cn.lang

**Comment by suoyukii** [comment]
I know all the features of Disenchanter, because I have a friend who likes fishing.

**Comment by Impelon** [comment]
I am not quite sure what you are trying to say...
I _am_ planning to add the chinese translation, but I haven't added it to the main branch yet, because I won't rebuild the mod for just one language-file and noone builds from github eitherway.

So again, as I have said. I already have a chinese translation as can be seen [here](https://github.com/Impelon/Disenchanter/commit/05b8add1c95a7b798d5f0d8c344e1fa37313fa7a) and do not need another one, if it is basically the same.

**Comment by suoyukii** [comment]
"驱魔" means to drive away or kill demons in Chinese. 

Voiding is not "作废". because "作废" means something like throwing it away as garbage. 

"msg.outdated.txt" feels like google translated it.

**Comment by Impelon** [comment]
I'm taking your word for it and merging your version now, thanks for your support! ^^

**Pull request merged**
